/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaswingproject;

import java.awt.print.PrinterException;
import static java.lang.Thread.sleep;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/**
 *
 * @author Arifeen Mahmud
 */
public class Restaurant extends javax.swing.JFrame {

    /**
     * Creates new form Restaurant
     */
    public Restaurant() {
        initComponents();
        setBounds(100, 100, 1100, 500);
        times();
    }

    public void times() {
        Thread dateTime = new Thread() {
            public void run() {

                try {
                    for (;;) {
                        Calendar cal = new GregorianCalendar();

                        int second = cal.get(Calendar.SECOND);
                        int minute = cal.get(Calendar.MINUTE);
                        int hours = cal.get(Calendar.HOUR);

                        time.setText("Time: " + hours + ":" + minute + ":" + second);
                        sleep(1000);

                    }

                } catch (Exception e) {
                }

            }
        };
        dateTime.start();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        FriedRice = new javax.swing.JLabel();
        Shawarma = new javax.swing.JLabel();
        Chicken = new javax.swing.JLabel();
        TxtFriedRice = new javax.swing.JTextField();
        TxtShawarma = new javax.swing.JTextField();
        TxtChicken = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnChooseDrink = new javax.swing.JComboBox<>();
        TxtChooseDrink = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        btnDelivery = new javax.swing.JCheckBox();
        btnTax = new javax.swing.JCheckBox();
        btnSubmit = new javax.swing.JButton();
        btnReset1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Selectcountry = new javax.swing.JComboBox<>();
        btnConvart = new javax.swing.JButton();
        btnReset2 = new javax.swing.JButton();
        TotalCostOfMeal = new javax.swing.JLabel();
        TotalCostOfDrink = new javax.swing.JLabel();
        CostOfDelivery = new javax.swing.JLabel();
        txtTotalCostOfMeal = new javax.swing.JLabel();
        txtTotalCostOfDrink = new javax.swing.JLabel();
        txtCostOfDelivery = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        Tax1 = new javax.swing.JLabel();
        SubTotal = new javax.swing.JLabel();
        Total = new javax.swing.JLabel();
        txtTax = new javax.swing.JLabel();
        txtSubTotal = new javax.swing.JLabel();
        txtTotal = new javax.swing.JLabel();
        txtEnterCurrencyOutput = new javax.swing.JLabel();
        txtEnterCurrency = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        time = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Menu");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(159, 98, 80, 34);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("QTY");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(263, 98, 74, 34);

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Price ৳");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(375, 98, 77, 34);

        FriedRice.setForeground(new java.awt.Color(255, 255, 255));
        FriedRice.setText("Fried Rice");
        jPanel2.add(FriedRice);
        FriedRice.setBounds(159, 150, 80, 28);

        Shawarma.setForeground(new java.awt.Color(255, 255, 255));
        Shawarma.setText("Shawarma");
        jPanel2.add(Shawarma);
        Shawarma.setBounds(159, 199, 80, 28);

        Chicken.setForeground(new java.awt.Color(255, 255, 255));
        Chicken.setText("Chicken");
        jPanel2.add(Chicken);
        Chicken.setBounds(159, 239, 80, 28);

        TxtFriedRice.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel2.add(TxtFriedRice);
        TxtFriedRice.setBounds(257, 150, 80, 28);

        TxtShawarma.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel2.add(TxtShawarma);
        TxtShawarma.setBounds(257, 199, 80, 28);

        TxtChicken.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel2.add(TxtChicken);
        TxtChicken.setBounds(257, 239, 80, 28);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("240৳");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(375, 150, 53, 28);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("85৳");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(375, 199, 53, 28);

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("60৳");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(375, 238, 53, 30);

        btnChooseDrink.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnChooseDrink.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Drinks", "Coca Cola", "Pepsi" }));
        jPanel2.add(btnChooseDrink);
        btnChooseDrink.setBounds(101, 274, 138, 28);

        TxtChooseDrink.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel2.add(TxtChooseDrink);
        TxtChooseDrink.setBounds(257, 273, 81, 28);

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("_");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(375, 274, 53, 28);

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator1);
        jSeparator1.setBounds(479, 98, 22, 267);

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator2);
        jSeparator2.setBounds(530, 194, 552, 2);

        btnDelivery.setBackground(new java.awt.Color(0, 0, 0));
        btnDelivery.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        btnDelivery.setForeground(new java.awt.Color(255, 255, 255));
        btnDelivery.setText("Delivery");
        jPanel2.add(btnDelivery);
        btnDelivery.setBounds(80, 340, 110, 31);

        btnTax.setBackground(new java.awt.Color(0, 0, 0));
        btnTax.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        btnTax.setForeground(new java.awt.Color(255, 255, 255));
        btnTax.setText("Tax");
        jPanel2.add(btnTax);
        btnTax.setBounds(200, 340, 60, 31);

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        jPanel2.add(btnSubmit);
        btnSubmit.setBounds(286, 332, 80, 40);

        btnReset1.setText("Reset");
        btnReset1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReset1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnReset1);
        btnReset1.setBounds(370, 332, 70, 41);

        jLabel11.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Restaurant");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(432, 69, 208, 23);

        jLabel12.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("currency conversion");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(629, 101, 253, 28);

        Selectcountry.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        Selectcountry.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Country", "Bangladesh", "India", "Pakestan" }));
        jPanel2.add(Selectcountry);
        Selectcountry.setBounds(510, 140, 140, 41);

        btnConvart.setText("Convart");
        btnConvart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvartActionPerformed(evt);
            }
        });
        jPanel2.add(btnConvart);
        btnConvart.setBounds(710, 140, 90, 41);

        btnReset2.setText("Reset");
        btnReset2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReset2ActionPerformed(evt);
            }
        });
        jPanel2.add(btnReset2);
        btnReset2.setBounds(930, 140, 90, 40);

        TotalCostOfMeal.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        TotalCostOfMeal.setForeground(new java.awt.Color(255, 255, 255));
        TotalCostOfMeal.setText("Total Cost Of Meal:");
        jPanel2.add(TotalCostOfMeal);
        TotalCostOfMeal.setBounds(511, 202, 160, 32);

        TotalCostOfDrink.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        TotalCostOfDrink.setForeground(new java.awt.Color(255, 255, 255));
        TotalCostOfDrink.setText("Total Cost Of Drink:");
        jPanel2.add(TotalCostOfDrink);
        TotalCostOfDrink.setBounds(511, 240, 136, 27);

        CostOfDelivery.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        CostOfDelivery.setForeground(new java.awt.Color(255, 255, 255));
        CostOfDelivery.setText("Cost Of Delivery:");
        jPanel2.add(CostOfDelivery);
        CostOfDelivery.setBounds(511, 273, 140, 27);

        txtTotalCostOfMeal.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        txtTotalCostOfMeal.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(txtTotalCostOfMeal);
        txtTotalCostOfMeal.setBounds(670, 200, 90, 32);

        txtTotalCostOfDrink.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtTotalCostOfDrink.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(txtTotalCostOfDrink);
        txtTotalCostOfDrink.setBounds(670, 240, 88, 27);

        txtCostOfDelivery.setBackground(new java.awt.Color(0, 0, 0));
        txtCostOfDelivery.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        txtCostOfDelivery.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(txtCostOfDelivery);
        txtCostOfDelivery.setBounds(670, 270, 88, 27);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator3);
        jSeparator3.setBounds(1096, 275, 24, 98);

        Tax1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        Tax1.setForeground(new java.awt.Color(255, 255, 255));
        Tax1.setText("Tax");
        jPanel2.add(Tax1);
        Tax1.setBounds(772, 202, 45, 22);

        SubTotal.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        SubTotal.setForeground(new java.awt.Color(255, 255, 255));
        SubTotal.setText("Sub Total");
        jPanel2.add(SubTotal);
        SubTotal.setBounds(772, 235, 80, 21);

        Total.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        Total.setForeground(new java.awt.Color(255, 255, 255));
        Total.setText("Total");
        jPanel2.add(Total);
        Total.setBounds(772, 267, 45, 21);

        txtTax.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        txtTax.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(txtTax);
        txtTax.setBounds(850, 200, 78, 30);

        txtSubTotal.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        txtSubTotal.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(txtSubTotal);
        txtSubTotal.setBounds(850, 230, 78, 30);

        txtTotal.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        txtTotal.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(txtTotal);
        txtTotal.setBounds(850, 270, 78, 30);

        txtEnterCurrencyOutput.setBackground(new java.awt.Color(0, 0, 0));
        txtEnterCurrencyOutput.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtEnterCurrencyOutput.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(txtEnterCurrencyOutput);
        txtEnterCurrencyOutput.setBounds(820, 140, 100, 41);
        jPanel2.add(txtEnterCurrency);
        txtEnterCurrency.setBounds(650, 140, 60, 41);

        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(890, 420, 80, 50);

        time.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        time.setForeground(new java.awt.Color(255, 255, 255));
        time.setText("Time");
        jPanel2.add(time);
        time.setBounds(785, 62, 189, 33);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(540, 330, 340, 150);

        jButton2.setText("Print");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(890, 360, 80, 50);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaswingproject/f220-MZ895595.jpg"))); // NOI18N
        jPanel2.add(jLabel4);
        jLabel4.setBounds(0, 0, 1250, 510);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1240, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:

        try {
            //=================Drink==============

            double drinks = Double.parseDouble(TxtChooseDrink.getText());
            double CocaCola = drinks * 40;
            double Pepsi = drinks * 45;

            if (btnChooseDrink.getSelectedItem().equals("Coca Cola")) {

                String Coca_Cola = String.format("%.2f", CocaCola);
                txtTotalCostOfDrink.setText(Coca_Cola);
            }
            if (btnChooseDrink.getSelectedItem().equals("Pepsi")) {

                String Pepsi_Cola = String.format("%.2f", Pepsi);
                txtTotalCostOfDrink.setText(Pepsi_Cola);
            }
            if (btnChooseDrink.getSelectedItem().equals("Choose Drinks")) {

                txtTotalCostOfDrink.setText("00");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please set a QTY and Drinks");
        }

        //================meal==================
        try {
            double FriedRice = Double.parseDouble(TxtFriedRice.getText());
            double PFriedRice = FriedRice * 240;
            String SPFriedRice = String.format("%.2f", PFriedRice);
            txtTotalCostOfMeal.setText(SPFriedRice);

            double Shawarma = Double.parseDouble(TxtShawarma.getText());
            double pShawarma = Shawarma * 85;
            String spShawarma = String.format("%.2f", pShawarma + PFriedRice);
            txtTotalCostOfMeal.setText(spShawarma);

            double Chicken = Double.parseDouble(TxtChicken.getText());
            double pChicken = Chicken * 60;
            String spChicken = String.format("%.2f", pShawarma + PFriedRice + pChicken);
            txtTotalCostOfMeal.setText(spChicken);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);

        }

        //===========Delivery===========
        double cDelivery = 18;
        if (btnDelivery.isSelected()) {
            String pDelivery = String.format("%.2f", cDelivery);
            txtCostOfDelivery.setText(pDelivery);
        } else {
            txtCostOfDelivery.setText("00");
        }

        //===========tax===========
        double txtTotalCostOfMeal = Double.parseDouble(this.txtTotalCostOfMeal.getText());
        double txtTotalCostOfDrink = Double.parseDouble(this.txtTotalCostOfDrink.getText());
        double txtCostOfDelivery = Double.parseDouble(this.txtCostOfDelivery.getText());
        double tax15 = ((txtTotalCostOfMeal + txtTotalCostOfDrink + txtCostOfDelivery) / 100) * 15;
        if (btnTax.isSelected()) {

            String tx = String.format("%.2f", tax15);
            txtTax.setText(tx);
        }

        //==============Sub Total=================
        double subtotal = txtTotalCostOfMeal + txtTotalCostOfDrink + txtCostOfDelivery;
        String Ssubtotal = String.format("%.2f", subtotal);

        txtSubTotal.setText(Ssubtotal);

        //============Total============
        double total = tax15 + subtotal;
        String stotal = String.format("%.2f", total);

        txtTotal.setText(stotal);
        
        
        //==========Recipt===========
        Double Invoice1 = Double.parseDouble(this.txtTotalCostOfMeal.getText());
        Double Invoice2 = Double.parseDouble(this.txtTotalCostOfDrink.getText());
        Double Invoice3 = Double.parseDouble(this.txtCostOfDelivery.getText());
        Double Invoice4 = Double.parseDouble(this.txtTax.getText());
        Double Invoice5 = Double.parseDouble(this.txtSubTotal.getText());
        Double Invoice6 = Double.parseDouble(this.txtTotal.getText());
        
        jTextArea1.append("\n Total Cost Info:\n"
                +"\n Total Cost Of Meal: \t" +Invoice1
                +"\n Total Cost Of Drink:\t" +Invoice2
                +"\n Cost Of Delivery:\t" +Invoice4
                +"\n Tax:\t\t" +Invoice5
                +"\n Sub Total:\t\t" +Invoice6
                +"\n Total:\t\t" +Invoice6
        
        
        );

    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnReset1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReset1ActionPerformed
        // TODO add your handling code here:
        TxtFriedRice.setText("");
        TxtShawarma.setText("");
        TxtChooseDrink.setText("");
        TxtChicken.setText("");
        
        txtTotalCostOfMeal.setText("");
        txtTotalCostOfDrink.setText("");
        txtCostOfDelivery.setText("");
        txtTax.setText("");
        txtSubTotal.setText("");
        txtTotal.setText("");

        btnDelivery.setSelected(false);
        btnTax.setSelected(false);
        btnChooseDrink.setSelectedItem("Choose Drinks");
        
        jTextArea1.setText("");
    }//GEN-LAST:event_btnReset1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed


    private void btnConvartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvartActionPerformed
        // TODO add your handling code here:
        try {
            double Bangladeshi = 89.07;
            double Indian = 77.64;
            double Pakistani = 200.10;
            double USD = Double.parseDouble(txtEnterCurrency.getText());

            if (Selectcountry.getSelectedItem().equals("Bangladesh")) {
                String bdt = String.format("BDT %.2f", USD * Bangladeshi);
                txtEnterCurrencyOutput.setText(bdt);
            }
            if (Selectcountry.getSelectedItem().equals("India")) {
                String Indiarupi = String.format("Rupi %.2f", USD * Indian);
                txtEnterCurrencyOutput.setText(Indiarupi);

            }
            if (Selectcountry.getSelectedItem().equals("Pakestan")) {
                String Pakestanirupi = String.format("Rupi %.2f", USD * Pakistani);
                txtEnterCurrencyOutput.setText(Pakestanirupi);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "please enter a ammunt");
        }


    }//GEN-LAST:event_btnConvartActionPerformed

    private void btnReset2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReset2ActionPerformed
        // TODO add your handling code here:
        txtEnterCurrency.setText("");
        txtEnterCurrencyOutput.setText("");
        Selectcountry.setSelectedItem("Select Country");

    }//GEN-LAST:event_btnReset2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            // TODO add your handling code here:

            Boolean print = jTextArea1.print();
        } catch (PrinterException ex) {
            Logger.getLogger(Restaurant.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Restaurant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Restaurant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Restaurant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Restaurant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Restaurant().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Chicken;
    private javax.swing.JLabel CostOfDelivery;
    private javax.swing.JLabel FriedRice;
    private javax.swing.JComboBox<String> Selectcountry;
    private javax.swing.JLabel Shawarma;
    private javax.swing.JLabel SubTotal;
    private javax.swing.JLabel Tax1;
    private javax.swing.JLabel Total;
    private javax.swing.JLabel TotalCostOfDrink;
    private javax.swing.JLabel TotalCostOfMeal;
    private javax.swing.JTextField TxtChicken;
    private javax.swing.JTextField TxtChooseDrink;
    private javax.swing.JTextField TxtFriedRice;
    private javax.swing.JTextField TxtShawarma;
    private javax.swing.JComboBox<String> btnChooseDrink;
    private javax.swing.JButton btnConvart;
    private javax.swing.JCheckBox btnDelivery;
    private javax.swing.JButton btnReset1;
    private javax.swing.JButton btnReset2;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JCheckBox btnTax;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel time;
    private javax.swing.JLabel txtCostOfDelivery;
    private javax.swing.JTextField txtEnterCurrency;
    private javax.swing.JLabel txtEnterCurrencyOutput;
    private javax.swing.JLabel txtSubTotal;
    private javax.swing.JLabel txtTax;
    private javax.swing.JLabel txtTotal;
    private javax.swing.JLabel txtTotalCostOfDrink;
    private javax.swing.JLabel txtTotalCostOfMeal;
    // End of variables declaration//GEN-END:variables
}
