
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Product extends javax.swing.JFrame {

    String driver = "oracle.jdbc.OracleDriver";
    String url = "jdbc:oracle:thin:@localhost:1521:orcl";

    //    String driver = "oracle.jdbc.OracleDriver";
//    String url = "jdbc:oracle:thin:@localhost:1521:orcl1";
    Connection con;
    Statement stm;
    PreparedStatement prstm;
    ResultSet rs;
    // ResultSetModel rsm = new ResultSetModel();
    DefaultTableModel dtm = new DefaultTableModel();
    String sqls = "";
    ResultSetModel rsm = new ResultSetModel();

    /**
     * Creates new form Product
     */
    public Product() {
        initComponents();
    }

    public void MyDriver() {
        try {
            Class.forName(driver);
            con = DriverManager.getConnection(url, "hr", "hr");
        } catch (ClassNotFoundException cnf) {
            System.out.println(cnf);
        } catch (SQLException sqle) {
            JOptionPane.showMessageDialog(null, sqle);
        }

    }

    /*
     * This _ethod will help to do any types of D_L operation in this product
     * class and into invoice class also
     */
    /*
     * public void runUpdate(String ss) { try { stm = con.createStatement();
     * stm.executeUpdate(ss); } catch (SQLException sqle) {
     * JOptionPane.showMessageDialog(null, sqle); } }
     *
     *
     * public ResultSet runQuery(String ss) { try { stm = con.createStatement();
     * rs = stm.executeQuery(ss); } catch (SQLException sqle) {
     * JOptionPane.showMessageDialog(null, sqle); } return rs; }
     *
     * public int stockInfo(String sqs) { int s = 0; rs = runQuery(sqs); try {
     * while (rs.next()) { s = rs.getInt("stok"); System.out.println(s); } }
     * catch (SQLException sqle) { JOptionPane.showMessageDialog(null, sqle); }
     * return s; }
     */
//This  _ethod is used to clear the entered value in a TextField
    public void clearFields() {
        pid.setText("");
        pname.setText("");
        stock.setText("");
        up.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        pname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        stock = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        up = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Save = new javax.swing.JButton();
        NS = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        Show = new javax.swing.JButton();
        update = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Product Information");
        setSize(new java.awt.Dimension(0, 0));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Product Information");

        jLabel2.setText("Product ID");

        pid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pidFocusGained(evt);
            }
        });

        jLabel3.setText("Product Name");

        pname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pnameFocusGained(evt);
            }
        });

        jLabel4.setText("Stock");

        jLabel5.setText("Unit Price");

        jTable1.setModel(rsm);
        jScrollPane1.setViewportView(jTable1);

        Save.setText("Save");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });

        NS.setText("New");
        NS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NSActionPerformed(evt);
            }
        });

        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        Show.setText("Show");
        Show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowActionPerformed(evt);
            }
        });

        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        jLabel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(206, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(119, 119, 119))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(Save)
                                .addGap(18, 18, 18)
                                .addComponent(NS)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                                .addComponent(Show)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(update)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(delete)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(exit)
                                .addContainerGap())
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(50, 50, 50)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel2)
                                                        .addComponent(jLabel3)
                                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel5))
                                                .addGap(22, 22, 22)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(pname, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(pid, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                .addComponent(up, javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(stock, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(27, 27, 27)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel1)
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(pid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(pname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(stock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5)
                                        .addComponent(up, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(Save)
                                        .addComponent(exit)
                                        .addComponent(delete)
                                        .addComponent(update)
                                        .addComponent(Show)
                                        .addComponent(NS))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {
        MyDriver();
        String s = "";

        try {
            stm = con.createStatement();
            rs = stm.executeQuery("select product_id from product where product_id=" + Integer.parseInt(pid.getText()) + "");
            while (rs.next()) {
                s = rs.getString("product_id");
            }
            if (s.equals(pid.getText())) {
                JOptionPane.showMessageDialog(null, "Exist");
            } else {
                sqls = "Insert into product values(" + Integer.parseInt(pid.getText()) + ",'" + pname.getText() + "',"
                        + Integer.parseInt(stock.getText()) + "," + Integer.parseInt(up.getText()) + ")";
                System.out.println(sqls);

                try {
                    stm = con.createStatement();
                    stm.executeUpdate(sqls);
                } catch (SQLException sqle) {
                    JOptionPane.showMessageDialog(null, sqle);
                }

            }

        } catch (SQLException sqle) {
            JOptionPane.showMessageDialog(null, sqle);
        }
        clearFields();
        Show();

    }

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {
        dispose();
    }

    private void NSActionPerformed(java.awt.event.ActionEvent evt) {
        clearFields();
    }

    private void ShowActionPerformed(java.awt.event.ActionEvent evt) {
        Show();

    }

    public void Show() {

        MyDriver();

        try {
            stm = con.createStatement();
            rs = stm.executeQuery("Select * from product");
        } catch (SQLException sqle) {
            JOptionPane.showMessageDialog(null, sqle);
        }

        rsm.dataResult(rs);

//        MyDriver();
//        try {
//            stm = con.createStatement();
//            rs = stm.executeQuery("SELECT * FROM product");
//            Vector<String> header = new Vector<String>();
//            header.add("Product ID");
//            header.add("Product name");
//            header.add("Stock");
//            header.add("Unit Price");
//            Vector<Vector<Object>> data = new Vector<Vector<Object>>();
//            while (rs.next()) {
//                Vector<Object> row = new Vector<Object>();
//                row.add(rs.getString("Pid"));
//                row.add(rs.getString("pname"));
//                row.add(rs.getString("stok"));
//                row.add(rs.getString("up"));
//                data.add(row); // add each result/row to data Vector
//            } // loop
//            dtm.setDataVector(data, header);
//        } catch (Exception e) {
//            System.out.println("Error in table: " + e);
//        }//try and catch
    }

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {
        MyDriver();
        int s = 0;
        sqls = "Select Stock from product where PRODUCT_ID="
                + Integer.parseInt(pid.getText());
        try {
            stm = con.createStatement();
            rs = stm.executeQuery(sqls);
        } catch (SQLException sqle) {
            JOptionPane.showMessageDialog(null, sqle);
        }
        try {
            while (rs.next()) {
                s = rs.getInt("Stock");

            }
        } catch (SQLException sqle) {
            JOptionPane.showMessageDialog(null, sqle);
        }
        int st = Integer.parseInt(stock.getText());
        int ns = s + st;
        try {
            sqls = "update product set Stock=? where PRODUCT_ID="
                    + Integer.parseInt(pid.getText());
            prstm = con.prepareStatement(sqls);
            prstm.setInt(1, ns);
            prstm.executeUpdate();
        } catch (SQLException sqle) {
            JOptionPane.showMessageDialog(null, sqle);
        }
    }

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {

        if (JOptionPane.showConfirmDialog(null, "Do you Delete") == 0) {
            sqls = "delete from product where PRODUCT_ID=" + Integer.parseInt(pid.getText());
            try {
                stm = con.createStatement();
                stm.executeUpdate(sqls);
            } catch (SQLException sqle) {
                JOptionPane.showMessageDialog(null, sqle);
            }
        }

    }

    private void pidFocusGained(java.awt.event.FocusEvent evt) {
        // TODO add your handling code here:

        jLabel6.setText("Product ID");

    }

    private void pnameFocusGained(java.awt.event.FocusEvent evt) {
        // TODO add your handling code here:

        jLabel6.setText("Product Name");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Product().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify
    private javax.swing.JButton NS;
    private javax.swing.JButton Save;
    private javax.swing.JButton Show;
    private javax.swing.JButton delete;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField pid;
    private javax.swing.JTextField pname;
    private javax.swing.JTextField stock;
    private javax.swing.JTextField up;
    private javax.swing.JButton update;
    // End of variables declaration
}
